name: Manual Deploy (PreProd)

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS region to deploy to'
        required: true
        type: choice
        options:
          - us-east-1
          - eu-west-2
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: 'plan'
      auto_approve:
        description: 'Auto approve apply/destroy operations'
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/terragrunt.yml
    with:
      module_path: lambda-build-module
      environment: preprod
      action: ${{ github.event.inputs.action }}
      auto_approve: ${{ github.event.inputs.auto_approve }}
      aws_region: ${{ github.event.inputs.region }}
    secrets: inherit
    
  build-apply:
    needs: build
    if: github.event.inputs.action == 'apply' && needs.build.result == 'success'
    uses: ./.github/workflows/terragrunt.yml
    with:
      module_path: lambda-build-module
      environment: preprod
      action: apply
      auto_approve: true
      aws_region: ${{ github.event.inputs.region }}
    secrets: inherit
    
  deploy:
    needs: [build, build-apply]
    if: |
      (github.event.inputs.action == 'plan' && needs.build.result == 'success') ||
      (github.event.inputs.action == 'apply' && needs.build-apply.result == 'success')
    uses: ./.github/workflows/terragrunt.yml
    with:
      module_path: lambda-deploy-module
      environment: preprod
      action: ${{ github.event.inputs.action }}
      auto_approve: ${{ github.event.inputs.auto_approve }}
      aws_region: ${{ github.event.inputs.region }}
    secrets: inherit 